---
version: '3.6'

services:
  jenkins:
    image: "jenkins/jenkins:lts"
    restart: always
    container_name: jenkins
    ports:
      - "8080:9000"
      - "50000:50000"
    environment: 
      TZ: Europe/Madrid
    volumes:
      - /root/docker/jenkins/:/var/jenkins_home
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /var/run/socker.sock:/var/run/docker.sock
    networks:
      - cicd_network

  nexus3:
    image: "sonatype/nexus3:latest"
    restart: always
    container_name: nexus3
    ports:
      - "8081:9001"
    environment: 
      TZ: Europe/Madrid
    volumes:
      - /root/docker/nexus:/nexus-data
    networks:
      - cicd_network

  sonarqube:
    image: "sonarqube:8.7.0-community"
    restart: always
    container_name: sonarqube
    expose:
      - "9000"
    ports:
      - "9000:9002"
    networks:
      - cicd_network
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /root/docker/sonarqube/data:/opt/sonarqube/data
      - /root/docker/sonarqube/extensions:/opt/sonarqube/extensions
      - /root/docker/sonarqube/logs:/opt/sonarqube/logs
      - /root/docker/sonarqube/temp:/opt/sonarqube/temp
      
  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - cicd_network
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /root/docker/postgresql:/var/lib/postgresql

  jira-server:
      image: 'atlassian/jira-software'
      restart: always
      container_name: jira
      depends_on:
        - db
      networks:
        - cicd_network
      environment:
        TZ: Europe/Madrid
        JIRA_JDBC_URL: jdbc:postgresql://db:5432/jira
        JIRA_JDBC_USERNAME: jira
        JIRA_JDBC_PASSWORD: jira
      volumes:
        - '/home/$USER/docker_data/jira:/var/atlassian/application-data/jira'
      ports:
        - '8080:9003'

networks:
  cicd_network:
    driver: bridge
