---
version: '3.6'

services:
  jenkins:
    image: "jenkins/jenkins:lts"
    restart: always
    container_name: jenkins
    ports:
      - "8100:8080"
      - "50000:50000"
    environment: 
      TZ: Europe/Madrid
    volumes:
      - /home/$USER/docker_data/jenkins/:/var/jenkins_home
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /var/run/socker.sock:/var/run/docker.sock
    networks:
      - my_network

  nexus3:
    image: "sonatype/nexus3:latest"
    restart: always
    container_name: nexus3
    ports:
      - "8101:8081"
      - "8083:8083"
    environment: 
      TZ: Europe/Madrid
    volumes:
      - "/home/$USER/docker_data/nexus:/nexus-data"
    networks:
      - my_network

  sonarqube:
    image: "sonarqube:8.2-community"
    restart: always
    container_name: sonarqube
    ports:
      - "8102:9000"
    networks:
      - my_network
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /home/$USER/docker_data/sonarqube/data:/opt/sonarqube/data
      - /home/$USER/docker_data/sonarqube/extensions:/opt/sonarqube/extensions
      - /home/$USER/docker_data/sonarqube/logs:/opt/sonarqube/logs
      - /home/$USER/docker_data/sonarqube/temp:/opt/sonarqube/temp
      
  db:
    image: postgres
    restart: always
    networks:
      - my_network
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /home/$USER/docker_data/postgresql:/var/lib/postgresql

  jira-server:
      image: 'atlassian/jira-software'
      restart: always
      container_name: jira
      depends_on:
        - db
      networks:
        - my_network
      environment:
        TZ: Europe/Madrid
        JIRA_JDBC_URL: jdbc:postgresql://db:5432/jira
        JIRA_JDBC_USERNAME: jira
        JIRA_JDBC_PASSWORD: jira
      volumes:
        - '/home/$USER/docker_data/jira:/var/atlassian/application-data/jira'
      ports:
        - '8103:8080'

networks:
  my_network:
    driver: bridge
      
